config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations", omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'

  resources :tickets do
    resources :payments, only: [:new, :create, :destroy]
    resources :confirmation, only: [:show]
  end

  resource :requests, only: [:new, :create, :destroy, :show]
  resource :reports, only: [:create, :show]

  get "users/verify", to: 'users#show_verify', as: 'show_verify'
  post "users/verify", to: 'users#verify', as: 'verify'
  post "users/resend", to: 'users#verify', as: 'resend'
  get 'users/validation', to: 'users#phone_validation', as: 'phone_validation'


  get '/dashboard', to: 'users#dashboard', as: 'dashboard'
  get '/request', to: 'users#dashboard'
  resources :users do
    resources :dashboard, only: [:show, :edit, :update]
  end

  post '/create_validation', to: 'users#create_validation'
  get 'tickets/:id/confirm', to: "tickets#confirmation", as: 'confirm'
  put 'tickets/:id/update', to: 'tickets#update', as: 'update'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  has_many :tickets
  has_many :requests
  after_create :send_welcome_email
  mount_uploader :photo, PhotoUploader
  mount_uploader :identitycard, PhotoUploader
  validates :email, presence: true, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true

  def name
    return "#{first_name} #{last_name}"
  end

  def verified?
    return verified
  end

   def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
  #  user_params[remote_avatar_url] = auth[:info][:image]
    user_params = user_params.to_h

    user = User.find_by(provider: auth.provider, uid: auth.uid)
    user ||= User.find_by(email: auth.info.email) # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end

  def avatar_url
    if facebook_picture_url
      return facebook_picture_url
    elsif photo_url
      return photo_url
    else
      return "https://cdn1.iconfinder.com/data/icons/user-pictures/100/female1-256.png"
    end
  end

  private

  def send_welcome_email
    UserMailer.welcome(self).deliver_now
  end



end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def home
  end

  def all
    @users = User.all
  end

  def dashboard
    @tickets = Ticket.all
    @buy_tickets = Ticket.where(buyer: current_user)
    @sell_tickets = Ticket.where(seller: current_user)
    @requests = current_user.requests
    @currentUser = current_user.id
  end

  def index

  end

  def edit
    @user = User.find(params[:id])
  end

   def update
    @user = User.find(params[:id])
    @user.update(user_params)
      redirect_to dashboard_path
  end

  def update_form
    @user = User.find(params[:id])
    @user.update(user_params)
  end

  def phone_validation
    # Create user on Authy, will return an id on the object
  end

  def create_validation
    @user = User.find(params[:user][:id])
    @user.update(user_params)
    redirect_to show_verify_path

  end

  def show_verify
    # also update user info i get from the form

    authy = Authy::API.register_user(
      email: current_user.email,
      cellphone: current_user.phone,
      country_code: current_user.country_code
    )

    current_user.update(authy_id: authy['id'])
    request = Authy::API.request_sms(id: current_user.authy_id)
  end

  def verify
    @user = current_user
    # Use Authy to send the verification token
    token = Authy::API.verify(id: @user.authy_id, token: params[:token])


    if token.ok?
      # Mark the user as verified for get /user/:id
      @user.update(verified: true)

      # Send an SMS to the user 'success'
      send_message("You did it! Signup complete :)")

      # Show the user profile
      redirect_to dashboard_path
    else
      Rails.logger.info token.errors
      flash.now[:danger] = "Incorrect code, please try again"
      render :show_verify
    end
  end



  def send_message(message)
    twilio_number = ENV['TWILIO_NUMBER']
    account_sid = ENV['TWILIO_ACCOUNT_SID']
    @client = Twilio::REST::Client.new account_sid, ENV['TWILIO_AUTH_TOKEN']

    @client.api.accounts(account_sid).messages.create(
      from: twilio_number,
      to: '+' + current_user.country_code + current_user.phone,
      body: message
    )
  end

  def resend
    @user = current_user
    Authy::API.request_sms(id: @user.authy_id)
    flash[:notice] = 'Verification code re-sent'
    redirect_to show_verify_path
  end



  private
    def user_params
      params.require(:user).permit(:email, :bankaccount, :phone, :identitycard, :first_name, :last_name, :photo, :country_code)
    end
end

app/views/users/phone_validation.html.erb
<div class="phone-container">
  <div class="ticket-container">
    <div class="row">
      <h4 class="text-center ">Sell by getting verified in 2 quick steps</h4>
      <br>
      <br>
      <div class="col-md-offset-3 col-md-6">
        <h5 class="text-center"> <i class="far fa-id-card"></i><b> Step 1: ID and phone verification</b></h5>
          <%= simple_form_for(current_user) do |f| %>
          <p>Please upload front side of your identity card</p>
            <%= f.input :identitycard, label: false %>
            <br>
            <%= f.input :photo_cache, as: :hidden %>
            <%= f.label :first_name, "First name " %>
              <%= f.text_field :first_name, class: "form-control ", placeholder: "#{current_user.first_name} ", :hint => "Please insert full legal name" %>
            <%= f.label :last_name, "Last name " %>
              <%= f.text_field :last_name, class: "form-control ", placeholder: "#{current_user.last_name} " %>
          <% end %>
      </div>
      <div class="col-md-offset-3 col-md-6">
        <%= form_for(current_user, url: create_validation_path, method: "post") do |f| %>
          <div class="form-group ">
            <%= f.label :country_code, "Country code" %>
              <%= f.text_field :country_code, class: "form-control", id: "authy-countries", placeholder: "Eg. 44" %>
          </div>
          <div class="form-group">
            <%= f.label :phone, "Phone number" %>
              <%= f.text_field :phone, class: "form-control", id: "authy-cellphone", placeholder: "Eg. 17621483811" %>
          </div>
          <%= f.hidden_field :id, :value => current_user.id %>
          <button class="verified-button">Next step <i class="fas fa-arrow-right"></i></button>
          <% end -%>
            <% if current_user.errors.any? %>
              <h2>Oops, something went wrong!</h2>
              <ul>
                <% current_user.errors.full_messages.each do |error| %>
                  <li>
                    <%= error %>
                  </li>
                  <% end -%>
              </ul>
              <% end -%>
      </div>
    </div>
  </div>
</div>

app/views/users/show_verify.html.erb
<div class="container">
  <div class="ticket-container">
    <div class="row">
      <div class="col-md-offset-3 col-md-6">
      <h5 class="text-center"> <i class="fas fa-mobile-alt"></i> <b>Step 2: Code verification</b></h5>
      <br>
      <p class="text-center">We have sent a SMS to the phone number you have provided, please insert the token code below.</p>
        <%= form_tag verify_path do %>
          <div class="form-group">
            <%= label_tag :code, "" %>
            <%= text_field_tag :token, '', class: "form-control" %>
          </div>
          <div class="phone-buttons">
          <button type="submit" class="verified-button"><i class="fas fa-check"></i> Verify code</button>
        <% end %>

        <%= form_tag resend_path do %>
          <button type="submit" class="btn btn-secondary"><i class="fas fa-recycle"></i> Resend code</button>
        <% end %>
      </div>
      </div>
    </div>
  </div>
</div>