config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations", omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'

  resources :tickets do
    resources :payments, only: [:new, :create, :destroy]
    resources :confirmation, only: [:show]
  end

  resource :requests, only: [:new, :create, :destroy, :show]
  resource :reports, only: [:create, :show]

  get "users/verify", to: 'users#show_verify', as: 'show_verify'
  post "users/verify", to: 'users#verify', as: 'verify'
  post "users/resend", to: 'users#verify', as: 'resend'
  get 'users/validation', to: 'users#phone_validation', as: 'phone_validation'


  get '/dashboard', to: 'users#dashboard', as: 'dashboard'
  get '/request', to: 'users#dashboard'
  resources :users do
    resources :dashboard, only: [:show, :edit, :update]
  end

  post '/create_validation', to: 'users#create_validation'
  get 'tickets/:id/confirm', to: "tickets#confirmation", as: 'confirm'
  put 'tickets/:id/update', to: 'tickets#update', as: 'update'

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
   <div class="fb-like" data-href="https://www.facebook.com/easyticks/" data-layout="button" data-action="recommend" data-size="large" data-show-faces="true" data-share="true"></div>
   <!--
   <a href="https://www.facebook.com/Easyticks-235753600530517/">  Follow us on <i class="fab fa-facebook-f"></i></a> -->
  </div>
  <div class="footer-copyright">
    <a href="easyticks.com" target="_blank"> Easyticks.com © 2018 </a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo transparent.png", height: 50 %>

      <% end %>



        <!-- Right Navigation -->
        <div class="navbar-wagon-right hidden-xs hidden-sm">
          <% if current_user %>
            <% if current_user.verified? %>
            <div class="btn-sell">
              <%= link_to "Sell Ticket", new_ticket_path, class: "navbar-wagon-item navbar-wagon-link sell-link" %>
            </div>
            <% elsif !current_user.verified? %>
              <div class="btn-sell">
              <%= link_to "Sell Ticket", phone_validation_path, class: "navbar-wagon-item navbar-wagon-link sell-link" %>
              </div>
            <% end  %>
            <% else  %>
              <div class="btn-sell">
              <%= link_to "Sell Ticket", new_user_session_path, class: "navbar-wagon-item navbar-wagon-link sell-link" %>
            </div>
          <% end %>

          <% if user_signed_in? %>

            <!-- Links when logged in -->

            <!-- Avatar with dropdown menu -->
            <div class="navbar-wagon-item">
              <div class="dropdown">
                <% avatar_url = current_user.facebook_picture_url || "http://placehold.it/30x30" %>
                  <%= image_tag current_user.avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
                    <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
                      <li>
                        <%= link_to dashboard_path do %>
                          <i class="fa fa-user"></i>
                          <%= t(".profile", default: "Dashboard") %>
                            <% end %>
                      </li>
                      <li>
                        <%= link_to destroy_user_session_path, method: :delete do %>
                          <i class="fas fa-sign-out-alt"></i>
                          <%= t(".sign_out", default: "Log out") %>
                            <% end %>
                      </li>
                    </ul>
              </div>
            </div>
            <% else %>
              <!-- Login link (when logged out) -->
              <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
                <% end %>
        </div>

        <!-- Dropdown list appearing on mobile only -->
        <div class="navbar-wagon-item hidden-md hidden-lg">
          <div class="dropdown">
            <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
            <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
              <li>
                <%= link_to dashboard_path do %>
                  <i class="fa fa-user"></i>
                  <%= t(".profile", default: "Dashboard") %>
                    <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="fas fa-sign-out-alt"></i>
                  <%= t(".sign_out", default: "Log out") %>
                    <% end %>
              </li>
            </ul>
          </div>
        </div>
</div>

app/views/shared/_review.html.erb
<%= simple_form_for([ user, review ], remote: true) do |form| %>
  <%= form.input :content %>
  <%= form.button :submit %>
<% end %>