config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations", omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'

  resources :tickets do
    resources :payments, only: [:new, :create, :destroy]
    resources :confirmation, only: [:show]
  end

  resource :requests, only: [:new, :create, :destroy, :show]
  resource :reports, only: [:create, :show]

  get "users/verify", to: 'users#show_verify', as: 'show_verify'
  post "users/verify", to: 'users#verify', as: 'verify'
  post "users/resend", to: 'users#verify', as: 'resend'
  get 'users/validation', to: 'users#phone_validation', as: 'phone_validation'


  get '/dashboard', to: 'users#dashboard', as: 'dashboard'
  get '/request', to: 'users#dashboard'
  resources :users do
    resources :dashboard, only: [:show, :edit, :update]
  end

  post '/create_validation', to: 'users#create_validation'
  get 'tickets/:id/confirm', to: "tickets#confirmation", as: 'confirm'
  put 'tickets/:id/update', to: 'tickets#update', as: 'update'

end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :buyer, class_name: "User", optional: true
  belongs_to :seller, class_name: "User", optional: true
  monetize :price_cents
  validates :date, presence: true
  validates :arrival_city, presence: true
  validates :departing_city, presence: true
  validates :booking_reference, presence: true, uniqueness: true
  validates :name_on_ticket, presence: true
end

def seller_url
    if facebook_picture_url
      return facebook_picture_url
    elsif photo_url
      return photo_url
    else
      return "https://cdn1.iconfinder.com/data/icons/user-pictures/100/female1-512.png"
    end
end

app/controllers/tickets_controller.rb
require 'timeout'

class TicketsController < ApplicationController

  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
     # if !params[:departing_city] && !params[:arrival_city] && !params[:date]
      # redirect_to new_requests_path
    # end

    @tickets = Ticket.where(departing_city: params[:departing_city], arrival_city: params[:arrival_city], date: params[:date]).order(date: :asc, time: :asc)
    if @tickets.empty?
      @other_tickets = Ticket.where(departing_city: params[:departing_city], arrival_city: params[:arrival_city]).order(date: :asc, time: :asc)
    end
    @users = User.all

  end

  def show
    @ticket = Ticket.find(params[:id])
    @seller_tickets_count = Ticket.where(seller_id: @ticket.seller.id).count
  end

  def counter
    @ticket_seller = ticket.seller_id
    counter = 0
    @ticket.seller_id.tickets.each do |ticket|
      counter = counter + 1
    end
    return counter
  end

  def new
    @ticket = Ticket.new
  end

  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.seller = current_user
    if @ticket.save
      redirect_to dashboard_path(:anchor => "#selling")
    else
      render :new
    end
  end

  def edit
    @ticket = Ticket.find(params[:id])
  end

  def update
    @ticket = Ticket.find(params[:ticket_id])
    @ticket.buyer = current_user_buyer
    @ticket.seller = current_user_seller
    @ticket.save
    redirect_to ticket_confirmation_path(@ticket)

  end

  def destroy
    @ticket = Ticket.find(params[:id])
    @ticket.destroy
    redirect_to dashboard_path(:anchor => "#selling")
  end

  def confirmation
    @ticket = Ticket.find(params[:id])
    require 'scrapifier'
    # bookingreference = @ticket.booking_reference
    # lastname = @ticket.name_on_ticket
    # url = "https://managebooking.eurostar.com/uk-en/dashboard?pnr=#{bookingreference}&surname=#{lastname}"
    url = "https://tickets.eurostar.com/tickets/SQMBOF/7133c742-06b1-40c4-8d64-b8f34b6dba20.pdf?response-content-type=application%2Fpdf&AWSAccessKeyId=AKIAIS4OAMU4IZGEPEAQ&Expires=1531849140&Signature=K%2FYJ%2FaE6jzBx3eKAy5a6Bvt5ycM%3D"
    @ticket_info = url.scrapify
  end

  private

  def ticket_params
    params.require(:ticket).permit(:user_id, :date, :time, :departing_city, :arrival_city, :price, :booking_reference, :name_on_ticket)
  end

end

app/views/tickets/confirmation.html.erb
<div class="container-fluid no-padding">
  <div class="row">
  <div class="col-md-12 no-padding">
      <img class="city-hero" src="https://i.imgur.com/yUNaVZb.jpg" class="img-responsive"/>
  </div>
    </div>
</div>

<div class="wrapper">
  <div class="container show-container">
    <div class="row">
      <div class="col-sm-offset-3 col-sm-6">
        <h2 class="text-center"><span class="lighter"> Booking confirmed! </span></h2>
        <p class="text-center"><span class="lighter">You're journey from <strong><%= @ticket[:departing_city] %></strong> to <strong><%= @ticket[:arrival_city] %></strong> on <strong><%= @ticket.date.strftime("%d %B %Y") %></strong> at <strong><%= @ticket.time %></strong> is confirmed.</span></p>
      </div>
      <div class="col-sm-offset-3 col-sm-6">
        <h4 class="text-center h3-name"><span class="lighter"><p>Name on ticket:
          <%= @ticket.name_on_ticket.upcase %>
        </p></span></h4>
      </div>
      <div class="col-sm-offset-3 col-sm-6">
        <h4 class="text-center"><span class="lighter">Booking reference:
          <%= @ticket.booking_reference %></span></h4>
      </div>
      <div class="col-sm-offset-3 col-sm-6 text-center download-div">
        <a class="btn-treehouse-confirmation" href="https://tickets.eurostar.com/tickets/SQMBOF/7133c742-06b1-40c4-8d64-b8f34b6dba20.pdf?response-content-type=application%2Fpdf&AWSAccessKeyId=AKIAIS4OAMU4IZGEPEAQ&Expires=1531849140&Signature=K%2FYJ%2FaE6jzBx3eKAy5a6Bvt5ycM%3D"
        download>
        <i class="fas fa-download"></i> Download your ticket </a>
      </div>
      <div class="col-sm-offset-3 col-sm-6 text-center">
        <div class="btn-dashboard dashboard-div">
          <%= link_to 'Dashboard', dashboard_path %>
        </div>
  </div>
</div>

app/views/tickets/index.html.erb
<div class="wrapper">

  <div class="search_form_index">
    <%= form_tag tickets_path, method: :get do %>
      <%= hidden_field_tag 'ticket' %>
        <%= select_tag "departing_city", options_for_select([ "London", "Paris", "Brussels", "Amsterdam" ], params[:departing_city] ? params[:departing_city] : "From"), prompt: "From", required: true %>
          <%= select_tag "arrival_city", options_for_select([ "Paris", "Brussels", "London", "Amsterdam" ], params[:arrival_city] ? params[:arrival_city] : "To"), prompt: "To", required: true %>
            <%= text_field_tag :date, nil, required: true, id: "datepicker-input", placeholder: params[:date] ? params[:date] : "Departing at              📅"%>
              <%= submit_tag 'Search', class: "form_submit" %>
                <% end %>

                <%= javascript_pack_tag 'datepicker' %>


    </div>

                    <div class="container">
                      <% if @tickets.length == 0 %>
                        <% if @other_tickets.length == 0  %>
                          <p class="empty-card-text-search">Your search has come up empty, sorry about that
                        </p>
                        <%else  %>
                      <p class="empty-card-text-search">Your search has come up empty, we've put other options below
                      </p>
                      <% end  %>
                      <p class="empty-card-text-search">

                        <%= link_to "Click here to get notified once a ticket shows up", dashboard_path(:anchor => "#request") %>
                      </p>

                        <% @other_tickets.each do |ticket| %>
                          <% if ticket.buyer_id == nil %>
                            <%= link_to ticket_path(ticket) do %>
                              <div class="card-ticket">
                                <div class="card-detail card-detail-user">
                                  <div class="card-information">
                                    <%= image_tag ticket.seller.avatar_url  %>
                                      <div class="card-information-details">
                                        <h2>
                                          <%= ticket.seller.first_name %>
                                            <%= ticket.seller.last_name.chars.first %>.
                                        </h2>
                                        <p class="verified">
                                          <i class="fas fa-user-check"></i> verified
                                        </p>
                                      </div>
                                  </div>
                                </div>
                                <div class="card-detail card-detail-expand card-detail-route">
                                  <div class="card-information">
                                    <h2>
                                       <%= ticket.date.strftime("%A, %b %d") %>
                                        <span>
                                           <%= ticket.time %>
                                        </span>
                                    </h2>
                                    <p class="route-information">
                                      <%= ticket.departing_city %>
                                        <span class="route-icon">➞</span>
                                        <%= ticket.arrival_city %>
                                    </p>
                                    <div class="card-information-route">
                                      <div class="line"></div>
                                      <p>
                                        <i class="far fa-circle"></i>
                                        <%= ticket.departing_city %> central station</p>
                                      <p>
                                        <i class="far fa-circle"></i>
                                        <%= ticket.arrival_city %> central station</p>
                                    </div>


                                  </div>
                                </div>
                                <div class="card-detail card-detail-price">
                                  <div class="card-information">
                                    <h2>
                                      <%= currency_symbol %><%= humanized_money(ticket.price) %>
                                    </h2>
                                    <p>Incl. VAT</p>
                                  </div>

                                </div>
                              </div>
                              <% end %>
                                <% end %>


                                <br>

                                  <% end %>

                      <% else %>
                        <% @tickets.each do |ticket| %>
                          <% if ticket.buyer_id == nil %>
                            <%= link_to ticket_path(ticket) do %>
                              <div class="card-ticket">
                                <div class="card-detail card-detail-user">
                                  <div class="card-information">
                                    <%= image_tag ticket.seller.avatar_url  %>
                                      <div class="card-information-details">
                                        <h2>
                                          <%= ticket.seller.first_name %>
                                            <%= ticket.seller.last_name.chars.first %>.
                                        </h2>
                                        <p class="verified">
                                          <i class="fas fa-user-check"></i> verified
                                        </p>
                                      </div>
                                  </div>
                                </div>
                                <div class="card-detail card-detail-expand card-detail-route">
                                  <div class="card-information">
                                    <h2>
                                      <i class="far fa-calendar-alt"></i> <%= ticket.date.strftime("%A, %b %d") %>
                                        <span>
                                          <i class="far fa-clock"></i> <%= ticket.time %>
                                        </span>
                                    </h2>
                                    <p class="route-information">
                                      <%= ticket.departing_city %>
                                        <span class="route-icon">➞</span>
                                        <%= ticket.arrival_city %>
                                    </p>
                                    <div class="card-information-route">
                                      <div class="line"></div>
                                      <p>
                                        <i class="far fa-circle"></i>
                                        <%= ticket.departing_city %> central station</p>
                                      <p>
                                        <i class="far fa-circle"></i>
                                        <%= ticket.arrival_city %> central station</p>
                                    </div>


                                  </div>
                                </div>
                                <div class="card-detail card-detail-price">
                                  <div class="card-information">
                                    <h2>
                                      <%= currency_symbol %><%= humanized_money(ticket.price) %>
                                    </h2>
                                    <p>Incl. VAT</p>
                                  </div>

                                </div>
                              </div>
                              <% end %>
                                <% end %>
                                  <% end %>

                      <% end %>
                    </div>


  </div>
</div>

app/views/tickets/new.html.erb
<div class="container">
  <div class="ticket-container">
    <div class="row">
      <div class="col-sm-offset-3 col-sm-6">

        <h2>Sell your ticket</h2>


        <%= simple_form_for [@ticket] do |f| %>

          <%= f.input :departing_city, :collection => %w[London Brussels Paris Amsterdam], prompt: "From", required: true %>
          <%= f.input :arrival_city, :collection => %w[London Brussels Paris Amsterdam], prompt: "To", required: true %>
          <%= f.input :date, as: :string, input_html: { id: 'datepicker-input'}, required: true %>
          <%= f.input :time, as: :string, input_html: { id: 'timepicker-input' }, required: true %>
          <%= f.input :booking_reference, as: :string, input_html: { maxlength: 6 }, placeholder: 'Eg. ABCDEF', :hint => "Booking reference must be 6 letters", required: true %>
          <%= f.input :name_on_ticket, as: :string, placeholder: 'Eg. Smith', :hint => "Last name only", required: true %>
          <%= f.input :price, input_html: { min: '1.0', step: 'any' }, :hint => "Resale price cannot exceed face value of ticket", required: true%>

          <%= f.submit "Sell", class: "ticket-action" %>

          <% end %>

      </div>
    </div>
  </div>
</div>

<%= content_for :after_js do %>
<%= javascript_pack_tag 'datepicker' %>
<%= javascript_pack_tag 'timepicker' %>
<% end %>

app/views/tickets/show.html.erb
<div class="container-fluid no-padding">
  <div class="row">
  <div class="col-md-12 no-padding">
    <% if @ticket[:arrival_city].downcase == "paris" %>
      <img class="city-hero" src="https://i.imgur.com/yHGEhDr.jpg" class="img-responsive"/>
    <% elsif @ticket[:arrival_city].downcase == "london" %>
      <img class="city-hero" src="https://i.imgur.com/OfTByzX.jpg" class="img-responsive"/>
    <% elsif @ticket[:arrival_city].downcase == "brussels" %>
      <img class="city-hero" src="https://i.imgur.com/VRCNBpr.jpg" class="img-responsive"/>
    <% elsif @ticket[:arrival_city].downcase == "amsterdam" %>
      <img class="city-hero" src="https://i.imgur.com/5Y6OpZf.jpg" class="img-responsive"/>
    <% end %>
  </div>
    </div>
</div>

<div class="wrapper-grey">
  <div class="container show-container">
    <div class="row">
      <div class="col-sm-offset-3 col-sm-6">
        <h2 class="text-center"><span class="lighter"><%= @ticket[:departing_city] %> → <%= @ticket[:arrival_city] %></span></h2>
        <p class="text-center"><span class="lighter">Departs: <%= @ticket.date.strftime("%A, %B, %d") %> at <%= @ticket.time %></span></p>
      </div>
      <div class="col-sm-offset-3 col-sm-6 text-center">
        <div class="card-user-show mx-auto d-block">
          <%= image_tag(@ticket.seller.avatar_url)  %>
        </div>
      </div>
      <div class="col-sm-offset-3 col-sm-6">
        <h3 class="text-center h3-name"><span class="lighter"><%= @ticket.seller.first_name %> <%= @ticket.seller.last_name.chars.first %>.</span></h3>
      </div>
      <div class="col-sm-offset-3 col-sm-6">
        <p class="text-center"><span class="lighter">Sold: <%= @seller_tickets_count %> tickets</span></p>
      </div>
      <div class="col-md-offset-3 col-md-3">
        <p class="text-center"><span class="lighter"><i class="fas fa-lock"></i> Secure payment</span></p>
      </div>
      <div class="col-md-3">
        <p class="text-center"><span class="lighter">
           <% if @ticket.seller.verified? %>
                <i class="fas fa-user-shield"></i> Verified seller</span>
            <% else -%>
            <% end -%>
            <% if !@ticket.seller.verified? %>
              <i class="fas fa-user-shield"></i> Verified seller</span>
           <% end %>
           </p>
      </div>
      <div class="divider div-transparent div-arrow-down"></div>
      <div class="col-sm-offset-3 col-sm-6">
        <h2 class="text-center"><%= humanized_money_with_symbol(@ticket.price) %></h2>
      </div>
      <div class="col-sm-offset-3 col-sm-6 text-center pay-col">
        <%= form_tag ticket_payments_path(@ticket) do %>
          <% if current_user %>
          <script src="https://checkout.stripe.com/checkout.js" class="stripe-button" data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-name="My Ticket" data-email="<%= current_user.email  %>" data-description="Ticket <%= @ticket_id %>" data-amount="<%= @ticket.price_cents %>"
            data-currency="<%= @ticket.price.currency %>"></script>
          <% end %>
        <% end %>
        <% if !current_user %>
          <%= link_to new_user_session_path do %>
            <button type="submit" class="stripe-button-el" style="visibility: visible;"><span style="display: block; min-height: 30px;">Pay with Card</span></button>
          <% end %>
        <% end %>
      </div>
  </div>
</div>

<% content_for :meta_title, "#{@ticket.price} ticket to #{@ticket.arrival_city} is being sold on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, "Ticket from #{@ticket.departing_city} to #{@ticket.arrival_city} on #{@ticket.date} at #{@ticket.time}, is being sold for #{@ticket.price}. Buy it now on easyticks.com, fast and safe !" %>
<% content_for :meta_image do %>
<%= image_url "logoog.png" %>
<% end %>